version: 2

models:

  - name: gold_daily_track_popularity
    description: >
      Gold table containing the daily popularity evolution of Christmas tracks.
      Used for time series analysis and trend visualization.
    config:
      materialized: table
      schema: GOLD
      tags: ["GOLD"]

    columns:
      - name: track_id
        data_type: string
      - name: track_name
        data_type: string
      - name: artist_id
        data_type: string
      - name: artist_name
        data_type: string
      - name: market
        data_type: string
      - name: popularity
        data_type: integer
      - name: record_date
        data_type: date


  - name: gold_artist_monthly_summary
    description: >
      Gold table summarizing artist performance over the Christmas season.
      Provides consolidated metrics for ranking and comparison.
    config:
      materialized: table
      schema: GOLD
      tags: ["GOLD"]

    columns:
      - name: artist_id
        data_type: string
      - name: artist_name
        data_type: string
      - name: market
        data_type: string
      - name: avg_popularity
        data_type: number
      - name: max_popularity
        data_type: number
      - name: min_popularity
        data_type: number
      - name: popularity_growth
        data_type: number
      - name: days_observed
        data_type: integer


  - name: gold_track_popularity_summary
    description: >
      Gold-level analytical table containing aggregated popularity metrics
      for tracks over the analysis period. This table preserves one row per
      track and is intentionally free of ranking or filtering logic, allowing
      flexible consumption and contextual ranking at the application layer.
    config:
      materialized: table
      schema: GOLD
      tags: ["GOLD"]

    columns:
      - name: track_id
        description: "Unique Spotify identifier for the track."
        data_type: string
        tests:
          - not_null
          - unique

      - name: track_name
        description: "Name of the track."
        data_type: string

      - name: artist_id
        description: "Unique Spotify identifier for the artist."
        data_type: string
        tests:
          - not_null

      - name: artist_name
        description: "Name of the artist."
        data_type: string

      - name: market
        description: "Market/region associated with the artist (e.g. BR, GB)."
        data_type: string
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['BR', 'GB']

      - name: avg_popularity
        description: "Average popularity of the track over the observation period."
        data_type: number

      - name: max_popularity
        description: "Maximum popularity reached by the track during the period."
        data_type: number

      - name: min_popularity
        description: "Minimum popularity observed for the track during the period."
        data_type: number

      - name: popularity_growth
        description: "Popularity growth calculated as max_popularity minus min_popularity."
        data_type: number

      - name: peak_date
        description: "Date when the track reached its peak popularity."
        data_type: date