version: 2

models:

  - name: gold_daily_track_popularity
    description: >
      Gold table containing the daily popularity evolution of Christmas tracks.
      Used for time series analysis and trend visualization.
    config:
      materialized: table
      schema: GOLD
      tags: ["GOLD"]

    columns:
      - name: track_id
        data_type: string
      - name: track_name
        data_type: string
      - name: artist_id
        data_type: string
      - name: artist_name
        data_type: string
      - name: market
        data_type: string
      - name: popularity
        data_type: integer
      - name: record_date
        data_type: date


  - name: gold_artist_monthly_summary
    description: >
      Gold table summarizing artist performance over the Christmas season.
      Provides consolidated metrics for ranking and comparison.
    config:
      materialized: table
      schema: GOLD
      tags: ["GOLD"]

    columns:
      - name: artist_id
        data_type: string
      - name: artist_name
        data_type: string
      - name: market
        data_type: string
      - name: avg_popularity
        data_type: number
      - name: max_popularity
        data_type: number
      - name: min_popularity
        data_type: number
      - name: popularity_growth
        data_type: number
      - name: days_observed
        data_type: integer


  - name: gold_top_christmas_tracks
    description: >
      Gold table ranking Christmas tracks based on popularity metrics
      aggregated over the analysis period.
    config:
      materialized: table
      schema: GOLD
      tags: ["GOLD"]

    columns:
      - name: track_id
        data_type: string
      - name: track_name
        data_type: string
      - name: artist_id
        data_type: string
      - name: artist_name
        data_type: string
      - name: market
        data_type: string
      - name: avg_popularity
        data_type: number
      - name: max_popularity
        data_type: number
      - name: min_popularity
        data_type: number
      - name: popularity_growth
        data_type: number
      - name: peak_date
        data_type: date
