SELECT
    $1 AS record,
    REGEXP_SUBSTR(METADATA$FILENAME, '\\d{4}-\\d{2}-\\d{2}')::DATE AS record_date,
    CURRENT_TIMESTAMP() AS ingested_at
FROM @SPOTIFY.RAW.GCS_BRONZE_STAGE/artists/
(FILE_FORMAT => SPOTIFY.RAW.JSON_FORMAT)
